// <auto-generated />
namespace DOICMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Complaint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Complaint));
        
        string IMigrationMetadata.Id
        {
            get { return "202104241348449_Complaint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
